# server/Dockerfile

# Use the official Node.js image as the base image
FROM node:16

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port used by the Express server
EXPOSE 8002

# Start the Express server
CMD ["npm", "start"]
